package com.agentmemory.model;

import java.time.Instant;
import java.util.List;

/**
 * A higher-tier memory artifact generated by consolidating raw observations.
 * Stored in {@code memory-consolidated} index with a deterministic ID derived
 * from the sorted list of source observation IDs (SHA-256).
 */
public class ConsolidatedArtifact {

    private String id;
    private String tier;
    private String content;
    private List<Double> embedding;
    private List<String> sourceIds;
    private String generatedBy;
    private Instant createdAt;
    private String sessionId;
    private List<String> tags;

    public ConsolidatedArtifact() {}

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getTier() { return tier; }
    public void setTier(String tier) { this.tier = tier; }

    public String getContent() { return content; }
    public void setContent(String content) { this.content = content; }

    public List<Double> getEmbedding() { return embedding; }
    public void setEmbedding(List<Double> embedding) { this.embedding = embedding; }

    public List<String> getSourceIds() { return sourceIds; }
    public void setSourceIds(List<String> sourceIds) { this.sourceIds = sourceIds; }

    public String getGeneratedBy() { return generatedBy; }
    public void setGeneratedBy(String generatedBy) { this.generatedBy = generatedBy; }

    public Instant getCreatedAt() { return createdAt; }
    public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }

    public String getSessionId() { return sessionId; }
    public void setSessionId(String sessionId) { this.sessionId = sessionId; }

    public List<String> getTags() { return tags; }
    public void setTags(List<String> tags) { this.tags = tags; }
}
